services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=Ecommerce_local'
      - 'POSTGRES_PASSWORD=Pandi*123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
